name: JoinEditor
version: '${project.version}'
main: me.jetby.joineditor.Main
api-version: '1.16'
authors: [MrJetby]
depend:
  - PlaceholderAPI
commands:
  joineditor:
    aliases:
      - je
    description: /joineditor customjoin/customquit/reload/test
  customjoin: {}
  customquit: {}