name: JoinEditor
version: '${project.version}'
main: me.jetby.joineditor.Main
api-version: '1.16'
description: 'by https://discord.gg/treexstudio'
authors: [MrJetby]
depend:
  - PlaceholderAPI
commands:
  joineditor:
    aliases:
      - je
    description: /joineditor reload/test
  customjoin: {}
  customquit: {}