


#  |  Права:
#  |   joineditor.admin - /joineditor reload
#  |   joineditor.customjoin - /joineditor customjoin
#  |   joineditor.customquit - /joineditor customquit


sounds:
  Join: ENTITY_WOLF_AMBIENT
  Quit: ENTITY_CAT_HURT
  CustomJoin: ENTITY_VILLAGER_YES
  CustomQuit: ENTITY_VILLAGER_NO

enables:
  join: true
  quit: true
  title: true
  subtitle: true
  motd: true
  commandsOnJoin:
    Player: true
    Console: true

commandsOnJoin:
  Player:
    - 'say Test command for %player%'
  Console:
    - 'say Test command from console for %player%'

settings:
  customjoin:
    - "&c&l&m-----------------------------"
    - " &c&l%player% &f%msg%"
    - "&c&l&m-----------------------------"
  customquit:
    - "&c&l&m-----------------------------"
    - " &c&l%player% &f%msg%"
    - "&c&l&m-----------------------------"

  join:
    - "&a&l&m-----------------------------"
    - " &a&l%player% &fзашёл на сервер."
    - "&a&l&m-----------------------------"
  quit:
    - "&a&l&m-----------------------------"
    - " &a&l%player% &fвышел с сервера."
    - "&a&l&m-----------------------------"

  title: "Добро пожаловать"
  subtitle: "Настройте в settings.yml"
  motd:
    - "&9&lВаш сервер"
    - "&f"
    - "&fДобро пожаловать, %player%"
    - "&fDiscord &bhttps://dsc.gg/treexstudio"
