

#  |  Permissions:
#  |   joineditor.admin - /joineditor reload
#  |   joineditor.customjoin
#  |   joineditor.customquit


enables:
  join: true
  quit: true
  title: true
  subtitle: true
  motd: true


settings:
  customjoin:
    - "&c&l&m-----------------------------"
    - " &c&l%player% &f%msg%"
    - "&c&l&m-----------------------------"
  customquit:
    - "&c&l&m-----------------------------"
    - " &c&l%player% &f%msg%"
    - "&c&l&m-----------------------------"

  join:
    - "&a&l&m-----------------------------"
    - " &a&l%player% &fjoined the server"
    - "&a&l&m-----------------------------"
  quit:
    - "&a&l&m-----------------------------"
    - " &a&l%player% &fleft the server"
    - "&a&l&m-----------------------------"

  title: "Welcome to server"
  subtitle: "Subtitle..."
  motd:
    - "&9&lYourServer"
    - "&f"
    - "&fWelcome, %player%"
    - "&fDiscord &bhttps://dsc.gg/treexstudio"
