


#  |  Права:
#  |   joineditor.admin - /joineditor reload
#  |   joineditor.customjoin - /joineditor customjoin
#  |   joineditor.customquit - /joineditor customquit


sounds:
  Join: ENTITY_WOLF_AMBIENT
  FirstJoin: ENTITY_WOLF_AMBIENT
  Quit: ENTITY_CAT_HURT
  CustomJoin: ENTITY_VILLAGER_YES
  CustomQuit: ENTITY_VILLAGER_NO

enables:
  FirstJoin: true
  join: true
  quit: true
  title: true
  subtitle: true
  motd: true
  commandsOnJoin:
    Player: true
    Console: true
  FirstJoinCommands:
    Player: true
    Console: true

FirstJoinCommands:
  Player:
    - 'say Test'
  Console:
    - 'say Test from console'
commandsOnJoin:
  Player:
    - 'say Test command for %player%'
  Console:
    - 'say Test command from console for %player%'

settings:
  customjoin:
    - "&c&l&m-----------------------------"
    - " &c&l%player% &f%msg%"
    - "&c&l&m-----------------------------"
  customquit:
    - "&c&l&m-----------------------------"
    - " &c&l%player% &f%msg%"
    - "&c&l&m-----------------------------"

  FirstJoin:
    - "&d&l&m-----------------------------"
    - " &d&l%player% &fвпервые зашёл на сервер."
    - "&d&l&m-----------------------------"
  join:
    - "&a&l&m-----------------------------"
    - " &a&l%player% &fзашёл на сервер."
    - "&a&l&m-----------------------------"
  quit:
    - "&a&l&m-----------------------------"
    - " &a&l%player% &fвышел с сервера."
    - "&a&l&m-----------------------------"

  title: "Добро пожаловать"
  subtitle: "Настройте в settings.yml"
  motd:
    - "&9&lВаш сервер"
    - "&f"
    - "&fДобро пожаловать, %player%"
    - "&fDiscord &bhttps://dsc.gg/treexstudio"









#      ВСЕ ТИПЫ
#      - '[MSG] Message'
#      - '[MSG_BROADCAST] Message'
#      - '[TITLE] First;Second'
#      - '[TITLE_BROADCAST] First;Second'
#      - '[ACTIONBAR] Message'
#      - '[ACTIONBAR_BROADCAST] Message'
#      - '[CONSOLE] give %player% diamond 2'
#      - '[PLAYER] menu'






Join:
  another:
    permission: joineditor.default
    actions:
      - '[MSG_BROADCAST] %player% зашёл на сервер'
      - '[TITLE] First;Second'
      - '[CONSOLE] give %player% emerald 2'
      - '[PLAYER] menu'
      - '[SOUND] SOUND_NAME'
  default:
    actions:
      - '[MSG] Message'
      - '[MSG_BROADCAST] Message'
      - '[TITLE] First;Second'
      - '[TITLE_BROADCAST] First;Second'
      - '[ACTIONBAR] Message'
      - '[ACTIONBAR_BROADCAST] Message'
      - '[CONSOLE] give %player% diamond 2'
      - '[PLAYER] menu'
      - '[SOUND] BLOCK_NOTE_BLOCK_BIT'
  firstjoin:
    enabled: true
    actions:
      - '[MSG] Message'
      - '[TITLE] Привет новичок;Добро пожаловать'
      - '[ACTIONBAR] Message'
      - '[CONSOLE] give %player% diamond 64'
